spring:
 profiles: "default"
 batch:
  table-prefix: SCHEMA.BATCH_
  job:
    enabled: false
 datasource:
  driverClassName: 'oracle.jdbc.driver.OracleDriver'
  username: onair
  password: nbcci
  url: jdbc:oracle:thin:@//HOST_NAME:PORT_NO/t123rpt
  maximum-pool-size: 20
  max-active: 10
  min-idle: 2
  max-idle: 5  
  max-wait: 10000
  testOnBorrow: true 
  validationQuery: "select 1 from dual" 
  validationInterval: 10000
 jpa:
  database-platform: 'org.hibernate.dialect.Oracle10gDialect'
  hibernate:
   ddl-auto: none
  show-sql: false
 data:
  elasticsearch:
   cluster-name: 
   cluster-nodes: 
   properties:
    indices:
     query:
      bool:
       max_clause_count: 100000
    userName: 
    password: 
server:
    compression:
        enabled: true   
        mime-types: text/html,text/css,application/javascript,application/json
indexname: "plan"
port: "N"
uniqueIndexName: ${vcap.application.application_uris:} 
filterParams: 1336009,1336008

management:
  security:
    enabled: false
    
security:
  basic:
    enabled: false  
  

